export { ProductDetailView } from "./product-detail-view"
export { ProductGallery } from "./product-gallery"
export { ProductInfo } from "./product-info"
export { ProductTabs } from "./product-tabs"
export { ProductFeatures } from "./product-features"
export { RelatedProducts, type RelatedProduct } from "./related-products"
export { MobileActionBar } from "./mobile-action-bar"
export { PageSkeleton } from "./page-skeleton"
export { productDetailService } from "./product-detail.service"
export { toProductDetail, toRelatedProductCard } from "./product-detail.mapper"
export { buildWhatsAppHref, buildConsultationHref } from "./product-detail.constants"